spring:
  profiles: default
server:
  port: 6082
  
  info:
    app_name: jupiter-main
    app_version: 0.0.1
foo:
   name:
      - 'fool1'
      - 'fool2'

jupiter: 
  //cache:
    ##最大2000个
    //maxSize: 2000
    ##超时时间300s
    //ttl: 300
  aop:
    proxy-target-class: true
  messages:
    basename: i18n/locales
  jpa:
    open-in-view: false
  mvc: 
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker: 
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  resources:
    static-locations: classpath:/static/,classpath:/templates/
    
  datasource: 
    ##druid
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.database}?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    type: com.alibaba.druid.pool.DruidDataSource
    username: ${db.username}
    password: ${db.password}
    maxActive: ${db.maxActive:20}
    minIdle: ${db.minIdle:1}
    testOnBorrow: false
    testOnReturn: false
    validationQuery: SELECT 1
    filters: wall,mergeStat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    ##hibernate
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    showSql: false
    
mybatis: 
  mapperLocations: classpath:jupiter-domain/*.xml
  typeAliasesPackage: com.jupiter.model