server:
    port: 6082
info:
    app_name: jupiter-main
    app_version: 0.0.1

spring:
  profiles: default
  aop:
    proxy-target-class: true
  messages:
    basename: i18n/locales
  jpa:
    open-in-view: false
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

jupiter: 
  datasource: 
    ##druid
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.1:3306/jupiter?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    maxActive: 100
    minIdle: 1
    testOnBorrow: false
    testOnReturn: false
    validationQuery: SELECT 1
    filters: wall,mergeStat
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    ##hibernate
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    showSql: false 
    
foo:
   name:
      - 'fool1'
      - 'fool2'
  

